### ISSUE TITLE
run_airsenal_optimization: best_squad referenced before assignment

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#148]
I started getting this error over the weekend, including on the master branch (where no changes have been made for a while). Possibly something to do with trying to run it again without deleting the database and starting from scratch if a new gameweek has started?

```
strategy: 100:  40%|█████████████████████████████████████████████████████████████████████▌                                                                                                        | 40.0/100 [00:10<00:15,  3.77it/s]Process Process-2:.00000000000001it [00:10, 18.59it/s]
Traceback (most recent call last):                                                                                                                                                  | 0.9523809523809523/100 [00:05<08:53,  5.38s/it]
  File "/Users/jroberts/opt/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap                                                                          | 2.0/100 [00:05<03:56,  2.41s/it]
    self.run()  73%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                           | 73.33333333333333/100 [00:10<00:02, 12.97it/s]
  File "/Users/jroberts/opt/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 99, in run                                                                                 | 40.0/100 [00:10<00:08,  7.01it/s]
    self._target(*self._args, **self._kwargs)                                                                                                                                        | 9.166666666666666/100 [00:10<01:00,  1.50it/s]
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/scripts/fill_transfersuggestion_table.py", line 78, in process_strat                                                               | 0.9523809523809523/100 [00:07<12:22,  7.50s/it]
    budget)21:   1%|█▎                                                                                                                                                              | 0.8333333333333334/100 [00:07<14:13,  8.61s/it]
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/optimization_utils.py", line 452, in apply_strategy                                                                     | 0.47619047619047616/100 [00:07<25:04, 15.12s/it]
    update_func_and_args=update_func_and_args                                                                                                                                                      | 3.0/100 [00:09<04:40,  2.90s/it]
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/optimization_utils.py", line 168, in make_optimum_transfer                                                               | 1.7391304347826086/100 [00:07<05:39,  3.45s/it]
    return best_squad, [best_pid_out], [best_pid_in]                                                                                                                                                   | 1/26 [00:00<00:05,  4.38it/s]
UnboundLocalError: local variable 'best_squad' referenced before assignment
```

In `optimization_utils.make_optimum_transfer` it looks like `best_squad` will be undefined if the loop over possible players to transfer finishes without finding a `total_points` value greater than 0.

**Comment by jack89roberts** [comment]
One case where you get this is if you try to run the optimisation across gameweeks we haven't done the prediction for - should add a useful error message for when that happens.

**Comment by jack89roberts** [comment]
This is the function to fix:
https://github.com/alan-turing-institute/AIrsenal/blob/5e56c2a8674a2add2d428b0c43193ca8f94b934f/airsenal/framework/optimization_utils.py#L133

Options:
- Initialise `best_team` to be a copy of `team`.
- Initialise `best_team` to `None`.
- Fail with a meaningful message that no viable transfer was found.

Need to check the consequences of the above in the rest of the optimisation code, i.e. what happens to the functions calling `make_optimum_transfer` if no transfer is found.

We should also:
- Raise an error if the prediction `tag` does not have predictions for a week in `gameweek_range`.
