### ISSUE TITLE
ZeroDivisionError in run_airsenal_predictions

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#173]
Applies to [117-player-attributes](https://github.com/alan-turing-institute/AIrsenal/tree/117-player-attributes) branch only.

Get this error from `run_airsenal_predictions`:

```
Traceback (most recent call last):
  File "/Users/jroberts/opt/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/jroberts/opt/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/scripts/fill_predictedscore_table.py", line 67, in allocate_predictions
    session
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/scripts/fill_predictedscore_table.py", line 42, in calc_predicted_points_for_pos
    df_player = get_fitted_player_model(player_model, pos, season, session)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 307, in get_fitted_player_model
    df_player, fits, reals = fit_player_data(player_model, position, season, session)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 452, in fit_player_data
    data, names = process_player_data(prefix, season, session)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 417, in process_player_data
    alpha = get_empirical_bayes_estimates(df)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 396, in get_empirical_bayes_estimates
    a0 = neff * (goals / team) * (total_minutes / minutes)
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/Users/jroberts/opt/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/jroberts/opt/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/scripts/fill_predictedscore_table.py", line 67, in allocate_predictions
    session
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/scripts/fill_predictedscore_table.py", line 42, in calc_predicted_points_for_pos
    df_player = get_fitted_player_model(player_model, pos, season, session)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 307, in get_fitted_player_model
    df_player, fits, reals = fit_player_data(player_model, position, season, session)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 452, in fit_player_data
    data, names = process_player_data(prefix, season, session)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 417, in process_player_data
    alpha = get_empirical_bayes_estimates(df)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 396, in get_empirical_bayes_estimates
    a0 = neff * (goals / team) * (total_minutes / minutes)
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "/Users/jroberts/opt/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/jroberts/opt/anaconda3/envs/airsenalenv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/scripts/fill_predictedscore_table.py", line 67, in allocate_predictions
    session
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/scripts/fill_predictedscore_table.py", line 42, in calc_predicted_points_for_pos
    df_player = get_fitted_player_model(player_model, pos, season, session)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 307, in get_fitted_player_model
    df_player, fits, reals = fit_player_data(player_model, position, season, session)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 452, in fit_player_data
    data, names = process_player_data(prefix, season, session)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 417, in process_player_data
    alpha = get_empirical_bayes_estimates(df)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/prediction_utils.py", line 396, in get_empirical_bayes_estimates
    a0 = neff * (goals / team) * (total_minutes / minutes)
ZeroDivisionError: division by zero
```

**Comment by jack89roberts** [comment]
Fixed by https://github.com/alan-turing-institute/AIrsenal/commit/fb20c2dc674d9cfb9acd5e1045b64c8423923345
