### ISSUE TITLE
setup_airsenal_database fails before the season starts

### ISSUE THREAD

**Issue by danarwix** [alan-turing-institute/AIrsenal#221]
When installing the database with no prior data, you get the following error:

```Filling Teams table from data in /Users/danar/PycharmProjects/AIrsenal_2/lib/python3.7/site-packages/airsenal/scripts/../data/teams_2021.csv
Traceback (most recent call last):
  File "/Users/danar/PycharmProjects/AIrsenal_2/bin/setup_airsenal_database", line 10, in <module>
    sys.exit(main())
  File "/Users/danar/PycharmProjects/AIrsenal_2/lib/python3.7/site-packages/airsenal/scripts/fill_db_init.py", line 18, in main
    make_team_table(session)
  File "/Users/danar/PycharmProjects/AIrsenal_2/lib/python3.7/site-packages/airsenal/scripts/fill_team_table.py", line 47, in make_team_table
    fill_team_table_from_file(filename, session)
  File "/Users/danar/PycharmProjects/AIrsenal_2/lib/python3.7/site-packages/airsenal/scripts/fill_team_table.py", line 24, in fill_team_table_from_file
    infile = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/danar/PycharmProjects/AIrsenal_2/lib/python3.7/site-packages/airsenal/scripts/../data/teams_2021.csv'
```

**Comment by jack89roberts** [comment]
Thanks and welcome @danarwix !

This is because we haven't got everything set up for the new season on the master branch yet, sorry about that. However, we do have it in our latest development version, which you should be able to install by doing the following from the `AIrsenal` directory on your system:
```
git checkout develop
pip install --upgrade --force-reinstall .
```

Note that as part of the development the names of most of the commands have changed, e.g. `setup_airsenal_database` is now `airsenal_setup_initial_db` ([this version of the README](https://github.com/alan-turing-institute/AIrsenal/tree/develop) has the updated command names). You may also see the error mentioned in #219 at the end of running the database setup - you can ignore that and continue to run predictions etc. normally afterwards.

Hope that helps, let me know if you have any other issues.

**Comment by jack89roberts** [comment]
The changes mentioned above are now on the master branch, so you can just pull the latest version and reinstall AIrsenal without needing to worry about the develop branch. From the AIrsenal directory (with your virtual environment activated):
```
git checkout master
git pull origin master
pip install --upgrade --force-reinstall .
rm /tmp/data.db
airsenal_setup_initial_db
```
