### ISSUE TITLE
airsenal_make_team --num_gw 3 is throwing an error

### ISSUE THREAD

**Issue by saba83rish** [alan-turing-institute/AIrsenal#230]
I did run the initial_setup and update_db steps but still the make_team command seems to fail with the below error 

>     "No predicted points in database - has the database been filled?"
> RuntimeError: No predicted points in database - has the database been filled?

**Comment by saba83rish** [comment]
Ah ok.
I went blindly by the read me file,

> Note that airsenal_run_optimization should only be used for transfer suggestions after the season has started. If it's before the season has started and you want to generate a full squad for gameweek one you should instead use:

airsenal_make_team --num_gw 3

It didn't say anything about `airsenal_run_prediction` let me try that.

**Comment by saba83rish** [comment]
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/airsenalenv/bin/airsenal_run_prediction", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 143, in main
    session, gw_range=gw_range, season=args.season, num_thread=args.num_thread
  File "/usr/local/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 107, in make_predictedscore_table
    calc_all_predicted_points(gw_range, season, tag, session)
  File "/usr/local/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 78, in calc_all_predicted_points
    model_team = get_fitted_team_model(season, session)
  File "/usr/local/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/bpl_interface.py", line 87, in get_fitted_team_model
    df_team = get_result_df(session)
  File "/usr/local/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/bpl_interface.py", line 33, in get_result_df
    for s in session.query(Result).all()
  File "/usr/local/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/bpl_interface.py", line 33, in <listcomp>
    for s in session.query(Result).all()
AttributeError: 'NoneType' object has no attribute 'date'

**Comment by saba83rish** [comment]
nm, i deleted the db file and created a new conda environment. reran everything from scratch and is working.

**Comment by jack89roberts** [comment]
Ok great, I'll close this issue but feel free to make another if you have any other problems.

And yes deleting and recreating the database is needed quite often at the moment, it's usually a good idea between gameweeks or if a new player has been added to the game.
