### ISSUE TITLE
airsenal_setup_initial_db  error price = gw1_data[0]["value"] IndexError: list index out of range

### ISSUE THREAD

**Issue by jeffendba** [alan-turing-institute/AIrsenal#256]
i have problem below when i try excute airsenal_setup_initial_db 
Data not available for player 50 week 1
Traceback (most recent call last):
  File "/root/anaconda3/envs/airsenalenv/bin/airsenal_setup_initial_db", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_db_init.py", line 27, in main
    fill_initial_team(session)
  File "/root/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/transaction_utils.py", line 47, in fill_initial_team
    price = gw1_data[0]["value"]
IndexError: list index out of range

**Comment by RajeshTailor1** [comment]
This is the same issue as [244](https://github.com/alan-turing-institute/AIrsenal/issues/244) take a look at that thread which also includes the solution.

**Comment by jeffendba** [comment]
@RajeshTailor1 
TQ it was solved with above error
