### ISSUE TITLE
_pickle.PicklingError: Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

### ISSUE THREAD

**Issue by nimrodmar** [alan-turing-institute/AIrsenal#259]
Each time I try to execute airsenal_run_prediction I get the following error. 
I've tried executing it with --num_thread=1 and it still didn't work.
I've saw a similar thread for Windows but my OS is mac. 

Would appreciate any assistance. 
```
airsenal_run_prediction --weeks_ahead 3

INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_8c4b3dae224ed40cd55af0e4da27a5f1 NOW.
Traceback (most recent call last):
  File "/Users/nimrodm/opt/anaconda3/bin/airsenal_run_prediction", line 8, in <module>
    sys.exit(main())
  File "/Users/nimrodm/opt/anaconda3/lib/python3.8/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 142, in main
    tag = make_predictedscore_table(
  File "/Users/nimrodm/opt/anaconda3/lib/python3.8/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 107, in make_predictedscore_table
    calc_all_predicted_points(gw_range, season, tag, session)
  File "/Users/nimrodm/opt/anaconda3/lib/python3.8/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 89, in calc_all_predicted_points
    processor.start()
  File "/Users/nimrodm/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/nimrodm/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/nimrodm/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/nimrodm/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/nimrodm/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/nimrodm/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/nimrodm/opt/anaconda3/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

```

**Comment by RajeshTailor1** [comment]
Hi @nimrodmar - Are you running this in the Conda environment? I can see references to python3.8 where as (I think) you should be running against Python 3.7 within the Conda environment.

**Comment by nimrodmar** [comment]
> Hi @nimrodmar - Are you running this in the Conda environment? I can see references to python3.8 where as (I think) you should be running against Python 3.7 within the Conda environment.

Yes, I have Python 3.8.3. 
Any idea how can I downgrade?

**Comment by jack89roberts** [comment]
Did you create and activate an "airsenalenv" conda environment? Try `conda activate airsenalenv`, then after that `which python` should return a path including `airsenalenv/bin/python` at the end, and `python --version` will return 3.7 if the conda environment was setup as described in the readme.

You'll need to activate the environment before running any AIrsenal commands. After doing that (as described above) does `airsenal_run_prediction --weeks_ahead 3` give the same error?

I'm not sure this is caused by using python 3.8 though, this may need more debugging as it's not something I've seen on Mac before.

**Comment by jack89roberts** [comment]
I also got this error in a python 3.8 conda environment on my Macbook. Note it's the same as the error we see on Windows #120 .
