### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'season

### ISSUE THREAD

**Issue by qamaheshkumar** [alan-turing-institute/AIrsenal#318]
Hi

On executing "airsenal_run_prediction --weeks_ahead 3" getting error "'NoneType' object has no attribute 'season'".

Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3\envs\airsenalenv\Scripts\airsenal_run_prediction-script.py", line 33, in <module>
    sys.exit(load_entry_point('airsenal', 'console_scripts', 'airsenal_run_prediction')())
  File "c:\users\admin\anaconda3\envs\airsenalenv\lib\site-packages\airsenal\scripts\fill_predictedscore_table.py", line 252, in main
    dbsession=session,
  File "c:\users\admin\anaconda3\envs\airsenalenv\lib\site-packages\airsenal\scripts\fill_predictedscore_table.py", line 188, in make_predictedscore_table
    dbsession=dbsession,
  File "c:\users\admin\anaconda3\envs\airsenalenv\lib\site-packages\airsenal\scripts\fill_predictedscore_table.py", line 89, in calc_all_predicted_points
    season, gameweek=min(gw_range), dbsession=dbsession
  File "c:\users\admin\anaconda3\envs\airsenalenv\lib\site-packages\airsenal\framework\bpl_interface.py", line 100, in get_fitted_team_model
    df_team = get_result_df(season, gameweek, dbsession)
  File "c:\users\admin\anaconda3\envs\airsenalenv\lib\site-packages\airsenal\framework\bpl_interface.py", line 37, in get_result_df
    for s in dbsession.query(Result).all()
  File "c:\users\admin\anaconda3\envs\airsenalenv\lib\site-packages\airsenal\framework\bpl_interface.py", line 39, in <listcomp>
    s.fixture.season,
AttributeError: 'NoneType' object has no attribute 'season'

-

**Comment by jack89roberts** [comment]
Hi @qamaheshkumar , did you fix your other problem with the missing team ID (#316 )? This may be related if something didn't work during the database setup. After doing that one, could you check whether you still get the error above after deleting and recreating the database?

1st delete the database. On Windows this can be in one of a few different places, try this to find the directory:
`python -c "from airsenal import TMPDIR; print(TMPDIR)"`
Delete the file `data.db` in the directory returned by that command (if that file exists).

Then run:
`airsenal_setup_initial_db`
Followed by:
`airenal_update_db`
And finally:
`airsenal_run_prediction --weeks_ahead 3`

If it still fails after that I'm not sure what the problem is but note that we have currently problems running AIrsenal on Windows. You may have more luck trying Windows subsystem for Linux (see the readme).
