### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by Bhaskaryechuri** [alan-turing-institute/AIrsenal#319]
When running the command "airsenal_run_optimization --weeks_ahead 1" earlier today, the following error message appears:

```
Unable to access FPL team history API
Traceback (most recent call last):
  File "//anaconda3/envs/airsenalenv/bin/airsenal_run_optimization", line 8, in <module>
    sys.exit(main())
  File "//anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 593, in main
    num_thread,
  File "//anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 368, in run_optimization
    num_free_transfers = get_free_transfers(gameweeks[0])
  File "//anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/utils.py", line 262, in get_free_transfers
    if "current" in data.keys() and len(data["current"]) > 0:
AttributeError: 'NoneType' object has no attribute 'keys'
```

PS: Running conda 4.8.5 on MacOS

**Comment by jack89roberts** [comment]
`Unable to access FPL team history API` normally means the FPL API was either not responding (e.g. this happens for about an hour after gameweek deadlines), or a problem with your internet connection. If you try again today are you still getting the same error?

We should make it exit more cleanly and add a helpful error message in this case.
