### ISSUE TITLE
airsenal_check_data: Cannot import name 'get_teams_for_season'

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#332]
I had the problem above before making any changes. I just tried removing everything then reinstalling, and I get the same thing:
```
Getting selected players in squad 5877683 for first gameweek...
DONE!
```
And when i try running `airsenal_check_data` after that, I get the following error msg:
 ```
Traceback (most recent call last):
 File "/Users/willknight/anaconda3/envs/airsenalenv/bin/airsenal_check_data", line 5, in <module>
    from airsenal.scripts.data_sanity_checks import run_all_checks
  File "/Users/willknight/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/scripts/data_sanity_checks.py", line 1, in <module>
    from airsenal.framework.utils import (
ImportError: cannot import name 'get_teams_for_season' from 'airsenal.framework.utils' (/Users/willknight/anaconda3/envs/airsenalenv/lib/python3.7/site-packages/airsenal/framework/utils.py)
```

Thanks for your help.

_Originally posted by @wknight in https://github.com/alan-turing-institute/AIrsenal/issues/329#issuecomment-750940874_

**Comment by jack89roberts** [comment]
Probably caused by `get_teams_for_season` being moved somewhere else, changing the import to reflect the new location should fix it, hopefully.
