### ISSUE TITLE
Team ID mismatch

### ISSUE THREAD

**Issue by Tdarnell** [alan-turing-institute/AIrsenal#398]
Environment: WSL Ubuntu 20.04
Command run: airsenal_run_pipeline --num_thread 16 --weeks_ahead 3 --clean --apply_transfers
Branch: main, develop
Python environment: System python 3.8.10
Steps taken to debug: 
- Deleted team ID file from AIrsenal/data/FPL_TEAM_ID
- deleted data.db

Team ID is defined in ~/.bashrc as: 
export FPL_TEAM_ID=1760571

```
Optimization complete..
Applying suggested transfers...
Traceback (most recent call last):
  File "/home/tom/.local/bin/airsenal_run_pipeline", line 8, in <module>
    sys.exit(run_pipeline())
  File "/home/tom/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/tom/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/tom/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tom/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/tom/.local/lib/python3.8/site-packages/airsenal/scripts/airsenal_run_pipeline.py", line 108, in run_pipeline
    transfers_ok = make_transfers(fpl_team_id)
  File "/home/tom/.local/lib/python3.8/site-packages/airsenal/scripts/make_transfers.py", line 290, in make_transfers
    transfer_player_ids, team_id, current_gw, chip_played = get_gw_transfer_suggestions(
  File "/home/tom/.local/lib/python3.8/site-packages/airsenal/scripts/make_transfers.py", line 85, in get_gw_transfer_suggestions
    raise Exception(
Exception: Team ID passed is 1760571, but transfer suggestions are for             team ID 1760571. We recommend re-running optimization.```

**Comment by Tdarnell** [comment]
It was fixed using: 

- pip install --force-reinstall .
