### ISSUE TITLE
Make transfers bug

### ISSUE THREAD

**Issue by Tdarnell** [alan-turing-institute/AIrsenal#410]
platform: Ubuntu WSL 20.04 (system python & Docker)

I am unable to run the make_transfers script, it results in the following error message: 

```Getting starting squad for 1760571
Traceback (most recent call last):
  File "/home/t/.local/bin/airsenal_run_pipeline", line 8, in <module>
    sys.exit(run_pipeline())
  File "/home/t/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/t/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/t/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/t/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/t/.local/lib/python3.8/site-packages/airsenal/scripts/airsenal_run_pipeline.py", line 103, in run_pipeline
    transfers_ok = make_transfers(fpl_team_id)
  File "/home/t/.local/lib/python3.8/site-packages/airsenal/scripts/make_transfers.py", line 302, in make_transfers
    post_transfer_bank = deduct_transfer_price(pre_transfer_bank, priced_transfers)
  File "/home/t/.local/lib/python3.8/site-packages/airsenal/scripts/make_transfers.py", line 44, in deduct_transfer_price
    gain = [transfer[0][1] - transfer[1][1] for transfer in priced_transfers]
  File "/home/t/.local/lib/python3.8/site-packages/airsenal/scripts/make_transfers.py", line 44, in <listcomp>
    gain = [transfer[0][1] - transfer[1][1] for transfer in priced_transfers]
KeyError: 0```

**Comment by Tdarnell** [comment]
I can see that the priced_transfers array is: 
[{'element_out': 164, 'selling_price': 70, 'element_in': 268, 'purchase_price': 70}]

Fixed by changing:
line 44: 
```gain = [transfer['selling_price'] - transfer['purchase_price'] for transfer in priced_transfers]```
and line 61 & 62:
```        t.add_row(["OUT", get_player_name(transfer['element_out']), f"£{transfer['selling_price']/10}"])
        t.add_row(["IN", get_player_name(transfer['element_in']), f"£{transfer['purchase_price']/10}"])```
        
I don't currently have git set-up correctly on my dev pc to send this as a pull request, I can do that tomorrow if the change hasn't been made :)

**Comment by Tdarnell** [comment]
Also noticed that get_player_id needs changing to get_player_from_api_id in lines 61 & 62

**Comment by jack89roberts** [comment]
Thanks @Tdarnell ! I'll try to take a look later today.
