### ISSUE TITLE
RuntimeError: Squad is incomplete

### ISSUE THREAD

**Issue by mildfuzz** [alan-turing-institute/AIrsenal#456]
Getting the following after running optimisation:

`docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=4891218" airsenal airsenal_run_optimization --weeks_ahead 3`

```
Traceback (most recent call last):
  File "/usr/local/bin/airsenal_run_optimization", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 776, in main
    run_optimization(
  File "/usr/local/lib/python3.8/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 560, in run_optimization
    t = print_team_for_next_gw(best_strategy, fpl_team_id)
  File "/usr/local/lib/python3.8/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 399, in print_team_for_next_gw
    t.get_expected_points(next_gw, tag)
  File "/usr/local/lib/python3.8/site-packages/airsenal/framework/squad.py", line 366, in get_expected_points
    self.optimize_lineup(gameweek, tag)
  File "/usr/local/lib/python3.8/site-packages/airsenal/framework/squad.py", line 353, in optimize_lineup
    raise RuntimeError("Squad is incomplete")
RuntimeError: Squad is incomplete
```

**Comment by mildfuzz** [comment]
Fixed by re-running  `docker build -t airsenal .`
