### ISSUE TITLE
Issue running optimiszation on latest build

### ISSUE THREAD

**Issue by mildfuzz** [alan-turing-institute/AIrsenal#466]
```
docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=4891218" airsenal airsenal_run_optimization --weeks_ahead 3
Logged in successfully
Running optimization with fpl_team_id 4891218
Unable to access FPL API
Traceback (most recent call last):
  File "/usr/local/bin/airsenal_run_optimization", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 776, in main
    run_optimization(
  File "/usr/local/lib/python3.8/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 436, in run_optimization
    num_free_transfers = get_free_transfers(
  File "/usr/local/lib/python3.8/site-packages/airsenal/framework/utils.py", line 292, in get_free_transfers
    return apifetcher.get_num_free_transfers(fpl_team_id)
  File "/usr/local/lib/python3.8/site-packages/airsenal/framework/data_fetcher.py", line 204, in get_num_free_transfers
    return squad_data["transfers"]["limit"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jack89roberts** [comment]
Hi @mildfuzz - are you still getting this? One thing that could cause it is if the FPL API was unavailable/there was a problem with your connection when you were running it.

**Comment by jack89roberts** [comment]
Actually, I get this error if running with an incorrect FPL username/password - could that be the case for you?
