### ISSUE TITLE
Sporadic "squad is incomplete"  errors in optimisation

### ISSUE THREAD

**Issue by jack89roberts** [alan-turing-institute/AIrsenal#469]
Happened near the end of the optimisation in the last gameweek (and then causes optimisation to hang as at least one of the strategies didn't create an output file). Not sure of the cause but has come up before. Perhaps either:
- Transfer functions failing to find a way to improve the initial squad (but I think this would usually lead to a different error, e.g. `best_squad undefined`).
- Something weird about the behaviour of adding and removing players in the `Squad` class - I think I remember seeing this error before and just the process of investigating it (without making changes apart from print statements etc.) seemed to fix it...

```
Traceback (most recent call last):█████████████████▍        | 76.19047619047603/100 [21:34<01:15,  3.19s/it]
  File "/Users/jroberts/opt/anaconda3/envs/airsenalenv/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap-1-2-1:  93%|███████████████████████████████▋  | 93.33333333333334/100 [21:43<00:11,  1.67s/it]
    self.run()2-0-2:  37%|████████████▎                    | 37.142857142857125/100 [21:21<00:04, 13.07it/s]
  File "/Users/jroberts/opt/anaconda3/envs/airsenalenv/lib/python3.8/multiprocessing/process.py", line 108, in rungy: 1-2-0-2-2:  29%|█████████▍                       | 28.571428571428573/100 [21:37<02:00,  1.69s/it]
    self._target(*self._args, **self._kwargs)              | 24.761904761904763/100 [21:38<02:59,  2.38s/it]
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/scripts/fill_transfersuggestion_table.py", line 185, in optimizeegy: 2-1-0-1-2:  93%|███████████████████████████████▋  | 93.33333333333312/100 [21:42<00:16,  2.41s/it]
    new_squad, transfers, points = make_best_transfers(     | 69.52380952380939/100 [21:31<00:00, 43.74it/s]
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/optimization_transfers.py", line 339, in make_best_transfers
    new_squad, players_out, players_in = make_optimum_single_transfer(
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/optimization_transfers.py", line 84, in make_optimum_single_transfer
    total_points += new_squad.get_expected_points(
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/squad.py", line 366, in get_expected_points
    self.optimize_lineup(gameweek, tag)
  File "/Users/jroberts/GitHub/AIrsenal/airsenal/framework/squad.py", line 353, in optimize_lineup
    raise RuntimeError("Squad is incomplete")
```

**Comment by jack89roberts** [comment]
In the loop below, if we fail to find a valid replacement player then `new_squad` will be incomplete after the loop:

https://github.com/alan-turing-institute/AIrsenal/blob/359ebbc2e52272fb1bedbd62a92c9e6fdb0b1981/airsenal/framework/optimization_transfers.py#L57-L72

**Comment by jack89roberts** [comment]
Failing to replace the cheapest available player does seem to be the problem in this case - the original squad contains Tsimikas, currently the cheapest player in the game at £3.7m and so can't be replaced unless the squad has money in the bank.
