### ISSUE TITLE
Issue on `sorted_transfers`

### ISSUE THREAD

**Issue by pentatonicfunk** [alan-turing-institute/AIrsenal#517]
```
====================================

Strategy for Team ID: 5232800
Baseline score: 164.31298646397062
Best score: 182.09600086636016
 ===============================================
 ========= Optimum strategy ====================
 ===============================================

 =========== Gameweek 6 ================

Chips played:  bench_boost

Players in:                     Players out:
-----------                     ------------
Gabriel Martinelli Silva                Rodrigo Moreno

 =========== Gameweek 7 ================

Chips played:  None

Players in:                     Players out:
-----------                     ------------
John Stones                     Reece James

 =========== Gameweek 8 ================

Chips played:  None

Players in:                     Players out:
-----------                     ------------
Bruno Borges Fernandes          Mohamed Salah

==========================
 Total score: 182 

Getting starting squad for 5232800

=== starting 11 ===


== GK ==

Alisson Ramses Becker (LIV)

== DEF ==

Trent Alexander-Arnold (LIV)
Nathan Collins (WOL)
Kyle Walker (MCI)

== MID ==

Marcus Rashford (MUN)
Pedro Lomba Neto (WOL)
Mohamed Salah (LIV)(VC)
Gabriel Martinelli Silva (ARS)

== FWD ==

Danny Welbeck (BHA)
Erling Haaland (MCI)(C)
Gabriel Fernando de Jesus (ARS)

=== subs ===

Reece James (CHE)
William Saliba (ARS)
Danny Ward (LEI)
Jacob Murphy (NEW)

Total progress:   2%|███▎                                                                                                                                                                             | 1/53 [09:37<8:20:42, 577.74s/it]
Optimization complete..
Applying suggested transfers...
Getting starting squad for 5232800
Traceback (most recent call last):
  File "/home/hendrawan/Green/AIrsenal/venv3.8/bin/airsenal_run_pipeline", line 8, in <module>
    sys.exit(run_pipeline())
  File "/home/hendrawan/Green/AIrsenal/venv3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/hendrawan/Green/AIrsenal/venv3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/hendrawan/Green/AIrsenal/venv3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hendrawan/Green/AIrsenal/venv3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/hendrawan/Green/AIrsenal/airsenal/scripts/airsenal_run_pipeline.py", line 149, in run_pipeline
    transfers_ok = make_transfers(fpl_team_id)
  File "/home/hendrawan/Green/AIrsenal/airsenal/scripts/make_transfers.py", line 297, in make_transfers
    sorted_priced_transfers = [
  File "/home/hendrawan/Green/AIrsenal/airsenal/scripts/make_transfers.py", line 298, in <listcomp>
    sorted_transfers_out[i] | sorted_transfers_in[i]
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

**Comment by jack89roberts** [comment]
Ah this is because we made a change that uses Python 3.9+ syntax, I've just changed it to be compatible with Python 3.8 so if you pull the repo and reinstall AIrsenal it  should work for you now @pentatonicfunk
