### ISSUE TITLE
RuntimeError: Squad is incomplete when running pipeline with free_hit_week flag

### ISSUE THREAD

**Issue by mildfuzz** [alan-turing-institute/AIrsenal#522]
Running: 

```
airsenal_run_pipeline --free_hit_week 8
```
returns:
```
Getting starting squad for 5165238
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/bin/airsenal_run_pipeline", line 8, in <module>
    sys.exit(run_pipeline())
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/airsenal_run_pipeline.py", line 140, in run_pipeline
    opt_ok = run_optimize_squad(
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/airsenal_run_pipeline.py", line 243, in run_optimize_squad
    run_optimization(
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 578, in run_optimization
    t = print_team_for_next_gw(best_strategy, season=season, fpl_team_id=fpl_team_id)
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 385, in print_team_for_next_gw
    t.get_expected_points(next_gw, tag)
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/framework/squad.py", line 374, in get_expected_points
    self.optimize_lineup(gameweek, tag)
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/framework/squad.py", line 361, in optimize_lineup
    raise RuntimeError("Squad is incomplete")
```

**Comment by mildfuzz** [comment]
Have pulled the latest `develop`

**Comment by jack89roberts** [comment]
@mildfuzz Have you setup your username and password the new way with `airsenal_env`?

**Comment by mildfuzz** [comment]
@jack89roberts I have now, same result

**Comment by nbarlowATI** [comment]
Hi @mildfuzz  hmm... this looks a bit strange.   Is there any other output in your terminal?   It would be good to know which bits of the `run_optimization` function in `airsenal/scripts/fill_transfersuggestion_table.py` are being run...   
If you have a bit of time, would you be willing to put a few debug print statements in there to help track this down?
Maybe `print(starting_squad)` sometime after line 449, and a `print(num_expected_outputs)` sometime after line 488, and maybe a few other print("got to here") ones thrown in for good measure?

**Comment by Sandipbgn** [comment]
I am also getting a similar error while running 
```bash
airsenal_run_optimization --weeks_ahead 3
```

if you got the solution, please share .

**Comment by ParallaX07** [comment]
Same error:
Getting starting squad for 692136
Traceback (most recent call last):
  File "/home/apollo/miniconda3/envs/airsenalenv/bin/airsenal_run_optimization", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/apollo/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 829, in main
    run_optimization(
  File "/home/apollo/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 606, in run_optimization
    best_squad = print_team_for_next_gw(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apollo/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 396, in print_team_for_next_gw
    t.get_expected_points(next_gw, tag)
  File "/home/apollo/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/framework/squad.py", line 396, in get_expected_points
    self.optimize_lineup(gameweek, tag)
  File "/home/apollo/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/framework/squad.py", line 383, in optimize_lineup
    raise RuntimeError("Squad is incomplete")
RuntimeError: Squad is incomplete

Note: I'm using Ubuntu-22.04.2 LTS through WSL

**Comment by jack89roberts** [comment]
@ParallaX07 @Sandipbgn sorry for the delay, could you confirm the following. Could you confirm the following:

1. Do you have a recommended strategy above the error message? Something like:

```
====================================

Strategy for Team ID: 1822891
Baseline score: 185.8936886660258
Best score: 191.54067033661735
 ===============================================
 ========= Optimum strategy ====================
 ===============================================

 =========== Gameweek 10 ================

Chips played:  None

Players in:			Players out:
-----------			------------
Lucas Digne			Ethan Pinnock

 =========== Gameweek 11 ================

Chips played:  None

Players in:			Players out:
-----------			------------
Phil Foden			Son Heung-min

 =========== Gameweek 12 ================

Chips played:  None

Players in:			Players out:
-----------			------------
Diogo Dalot Teixeira		Joel Matip

==========================
 Total score: 191
```

2. Are the transfers it suggests you to make this week valid? I.e. could you afford them/would they leave your squad in a valid state?

3. Have you made any transfers already this gameweek before running airsenal?

4. Do you also get this error message if running `airsenal_run_pipeline`?

**Comment by jack89roberts** [comment]
My theory is it's when people have already made transfers in the gameweek as I get it for our team now having put out transfers in for this week. Will make a separate issue for it.

**Comment by ParallaX07** [comment]
@jack89roberts you are correct. The error happens after the recommended strategy is given, and as far as I've checked it does give a valid recommendation.
```
====================================

Strategy for Team ID: 692136
Baseline score: 177.86280096371968
Best score: 185.59238789452448
 ===============================================
 ========= Optimum strategy ====================
 ===============================================

 =========== Gameweek 10 ================

Chips played:  None

Players in:                     Players out:
-----------                     ------------
Alexis Mac Allister                     Mathias Jensen

 =========== Gameweek 11 ================

Chips played:  None

Players in:                     Players out:
-----------                     ------------
James Ward-Prowse                       Moussa Diaby

 =========== Gameweek 12 ================

Chips played:  None

Players in:                     Players out:
-----------                     ------------
Diogo Dalot Teixeira            Joel Matip

==========================
 Total score: 185

Getting starting squad for 692136
Traceback (most recent call last):
  File "/home/apollo/miniconda3/envs/airsenalenv/bin/airsenal_run_optimization", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/apollo/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 829, in main
    run_optimization(
  File "/home/apollo/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 606, in run_optimization
    best_squad = print_team_for_next_gw(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apollo/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 396, in print_team_for_next_gw
    t.get_expected_points(next_gw, tag)
  File "/home/apollo/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/framework/squad.py", line 396, in get_expected_points
    self.optimize_lineup(gameweek, tag)
  File "/home/apollo/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/framework/squad.py", line 383, in optimize_lineup
    raise RuntimeError("Squad is incomplete")
RuntimeError: Squad is incomplete
Total progress:   5%|███▏                                                               | 1/21 [01:55<38:22, 115.14s/it]
```
and it gives this error for both `airsenal_run_optimization --weeks_ahead 3` and `airsenal_run_pipeline`
