### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by pentatonicfunk** [alan-turing-institute/AIrsenal#541]
after last update
```
git log --oneline

b208c89 (HEAD -> main, origin/main, origin/HEAD) Merge pull request #518 from alan-turing-institute/develop
380af8f bump version number
```

i got this error that looks like SQL related when running pipeline
```
airsenal_run_pipeline --weeks_ahead 3 --num_thread 8 --apply_transfers                                                                 ✔  venv3.8  
Running for FPL Team ID 5232800
Found pre-existing AIrsenal database.
Updating database..
Updating player table...
Updating player Ed Turns
Traceback (most recent call last):
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: player_mapping.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~AIrsenal/venv3.8/bin/airsenal_run_pipeline", line 8, in <module>
    sys.exit(run_pipeline())
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "~AIrsenal/airsenal/scripts/airsenal_run_pipeline.py", line 137, in run_pipeline
    update_ok = update_database(fpl_team_id, update_attr, dbsession)
  File "~AIrsenal/airsenal/scripts/airsenal_run_pipeline.py", line 205, in update_database
    return update_db(season, attr, fpl_team_id, dbsession)
  File "~AIrsenal/airsenal/scripts/update_db.py", line 165, in update_db
    num_new_players = update_players(season, session)
  File "~AIrsenal/airsenal/scripts/update_db.py", line 107, in update_players
    return add_players_to_db(
  File "~AIrsenal/airsenal/scripts/update_db.py", line 125, in add_players_to_db
    p = find_player_in_table(name, dbsession=dbsession)
  File "~AIrsenal/airsenal/scripts/fill_player_table.py", line 26, in find_player_in_table
    mapping = dbsession.query(PlayerMapping).filter_by(alt_name=name).first()
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2823, in first
    return self.limit(1)._iter().first()
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "~AIrsenal/venv3.8/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: player_mapping.id
[SQL: SELECT player_mapping.id AS player_mapping_id, player_mapping.player_id AS player_mapping_player_id, player_mapping.alt_name AS player_mapping_alt_name 
FROM player_mapping 
WHERE player_mapping.alt_name = ?
 LIMIT ? OFFSET ?]
[parameters: ('Martial Godo', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

does it mean i need to reinit the DB ?

**Comment by pentatonicfunk** [comment]
so i ran `airsenal_setup_initial_db --clean` and it seems after that, pipeline worked fine

**Comment by jack89roberts** [comment]
Ah yes sorry, we should have flagged this - the recent changes added some columns to the database so it's necessary to do a clean run.
