### ISSUE TITLE
Crash when printing team after free hit

### ISSUE THREAD

**Issue by nbarlowATI** [alan-turing-institute/AIrsenal#59]
In optimization, after playing free hit for next gw and making 14 transfers, get crash when printing the optimum team:
```
Traceback (most recent call last):
  File "/Users/nbarlow/anaconda3/bin/run_airsenal_optimization", line 10, in <module>
    sys.exit(main())
  File "/Users/nbarlow/anaconda3/lib/python3.6/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 279, in main
    print_team_for_next_gw(best_strategy)
  File "/Users/nbarlow/anaconda3/lib/python3.6/site-packages/airsenal/scripts/fill_transfersuggestion_table.py", line 145, in print_team_for_next_gw
    expected_points = t.get_expected_points(next_gw,tag)
  File "/Users/nbarlow/anaconda3/lib/python3.6/site-packages/airsenal/framework/team.py", line 259, in get_expected_points
    raise RuntimeError("Team is incomplete")
RuntimeError: Team is incomplete
```
why is the team incomplete?

**Comment by nbarlowATI** [comment]
This was because I hadn't run "update_airsenal_db" to get the correct current team.
