### ISSUE TITLE
When Trying to make the transfers it errors out

### ISSUE THREAD

**Issue by AbdullaMashaly** [alan-turing-institute/AIrsenal#612]
Traceback (most recent call last):
  File "/Users/abdullamashaly/anaconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/make_transfers.py", line 350, in main
    make_transfers(args.fpl_team_id, confirm)
  File "/Users/abdullamashaly/anaconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/make_transfers.py", line 331, in make_transfers
    if skip_check or check_proceed(len(sorted_priced_transfers)):
UnboundLocalError: local variable 'sorted_priced_transfers' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/abdullamashaly/anaconda3/envs/airsenalenv/bin/airsenal_make_transfers", line 8, in <module>
    sys.exit(main())
  File "/Users/abdullamashaly/anaconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/make_transfers.py", line 353, in main
    raise Exception(
Exception: Something went wrong when making transfers. Check your team and make transfers and lineup changes manually on the web-site. If the problem persists, let us know on GitHub.

**Comment by jack89roberts** [comment]
Hi @AbdullaMashaly , this should now be fixed if you pull and install the latest AIrsenal version by doing this from the parent AIrsenal directory:

```
conda activate airsenalenv
git pull
pip install --force-reinstall .
```
