### ISSUE TITLE
Issue with cleaning DB

### ISSUE THREAD

**Issue by mildfuzz** [alan-turing-institute/AIrsenal#613]
`╰─❯ airsenal_setup_initial_db --clean
Cleaning database..
Filling Teams table from data in /usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/../data/teams_2324.csv
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/bin/airsenal_setup_initial_db", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/fill_db_init.py", line 57, in main
    make_init_db(args.fpl_team_id, dbsession)
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/fill_db_init.py", line 27, in make_init_db
    make_team_table(dbsession=dbsession)
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/fill_team_table.py", line 46, in make_team_table
    fill_team_table_from_file(filename, dbsession=dbsession)
  File "/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/fill_team_table.py", line 18, in fill_team_table_from_file
    infile = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Caskroom/miniconda/base/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/../data/teams_2324.csv'`

Trying to turn it off and back on again (because of other errors) and I see the above errors

**Comment by jack89roberts** [comment]
Hi @mildfuzz , are you on the latest airsenal version (updated yesterday)? We've had to fix various things for the new season.  If you `git pull` and then `pip install --force-reinstall -e .` from the parent AIrsenal directory with your conda environment activated it should work.

But I will check this function when I'm back at my laptop as I've only tested the run pipeline script recently, not the separate DB setup script.

**Comment by jack89roberts** [comment]
I think your conda environment wasn't activated, can you try `conda activate airsenalenv` and then running the pip install? If that still doesn't work can you check what `which python` (should be a path containing airsenalenv) and `python --version` (should be 3.9.x) return?

**Comment by mildfuzz** [comment]
worked a charm
