### ISSUE TITLE
Deprecated postgres:// URI

### ISSUE THREAD

**Issue by Tdarnell** [alan-turing-institute/AIrsenal#620]
SQLAlchemy 1.4 removed the deprecated postgres dialect name, the name postgresql must be used instead now. The dialect is the part before the :// in the URL. SQLAlchemy 1.3 and earlier showed a deprecation warning but still accepted it.

https://stackoverflow.com/questions/62688256/sqlalchemy-exc-nosuchmoduleerror-cant-load-plugin-sqlalchemy-dialectspostgre

**Comment by jack89roberts** [comment]
Thanks for the issue and fix @Tdarnell , FYI we have had some other issues with running AIrsenal with a PostgreSQL database in the past, off the top of my head I think mostly performance/multiprocessing problems (the most likely place you'll see that if you try to run the optimisation).

**Comment by Tdarnell** [comment]
It does seem Postgresql is still problematic, seems related to this: 

https://stackoverflow.com/questions/41279157/connection-problems-with-sqlalchemy-and-multiple-processes

There are suggested fixes, but I'm not sure how well they will work with the intended sqlite usage.

**Comment by jack89roberts** [comment]
#346, #168 are the old related issues, but it's always felt like it would be a headache to try to fix (plus whatever's in those issues may be irrelevant with the current version of sqlalchemy etc.) Does it still work if you run it single-threaded?

**Comment by Tdarnell** [comment]
@jack89roberts No single threaded does not work, but with a different traceback:

<details>
  <summary>Traceback</summary>

  ```
  Traceback (most recent call last):
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2108, in _exec_insertmany_context
      dialect.do_execute(
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute     
      cursor.execute(statement, parameters)
  psycopg2.ProgrammingError: can't adapt type 'ArrayImpl'

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/mnt/d/Code/AI/AIrsenal/.venv/bin/airsenal_run_pipeline", line 8, in <module>
      sys.exit(run_pipeline())
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/mnt/d/Code/AI/AIrsenal/airsenal/scripts/airsenal_run_pipeline.py", line 159, in run_pipeline
      predict_ok = run_prediction(num_thread, gw_range, dbsession)
    File "/mnt/d/Code/AI/AIrsenal/airsenal/scripts/airsenal_run_pipeline.py", line 239, in run_prediction
      tag = make_predictedscore_table(
    File "/mnt/d/Code/AI/AIrsenal/airsenal/scripts/fill_predictedscore_table.py", line 195, in make_predictedscore_table        
      calc_all_predicted_points(
    File "/mnt/d/Code/AI/AIrsenal/airsenal/scripts/fill_predictedscore_table.py", line 175, in calc_all_predicted_points        
      dbsession.commit()
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1920, in commit
      trans.commit(_to_root=True)
    File "<string>", line 2, in commit
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
      ret_value = fn(self, *arg, **kw)
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1236, in commit
      self._prepare_impl()
    File "<string>", line 2, in _prepare_impl
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
      ret_value = fn(self, *arg, **kw)
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1211, in _prepare_impl    
      self.session.flush()
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
      self._flush(objects)
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4298, in _flush
      with util.safe_reraise():
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__     
      raise exc_value.with_traceback(exc_tb)
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
      flush_context.execute()
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute        
      rec.execute(self)
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute        
      util.preloaded.orm_persistence.save_obj(
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj       
      _emit_insert_statements(
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
      result = connection.execute(
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
      return meth(
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
      return connection._execute_clauseelement(
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
      ret = self._execute_context(
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1839, in _execute_context 
      return self._exec_insertmany_context(
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2116, in _exec_insertmany_context
      self._handle_dbapi_exception(
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
      raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2108, in _exec_insertmany_context
      dialect.do_execute(
    File "/mnt/d/Code/AI/AIrsenal/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute     
      cursor.execute(statement, parameters)
  sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'ArrayImpl'
  [SQL: INSERT INTO player_prediction (fixture_id, predicted_points, tag, player_id) SELECT p0::INTEGER, p1::FLOAT, p2::VARCHAR, p3::INTEGER FROM (VALUES (%(fixture_id__0)s, %(predicted_points__0)s, %(tag__0)s, %(player_id__0)s, 0), (%(fixture_id__1)s, %(pre ... 88368 characters truncated ...  p3, sen_counter) ORDER BY sen_counter RETURNING player_prediction.id, player_prediction.id AS id__1]
  [parameters: {
  ...
  }]
  (Background on this error at: https://sqlalche.me/e/20/f405)
  ```
  
</details>

I'd be quite keen to use postgres so I can run some jaxlib and GMO non-dependant portions of the code from a raspberry pi throughout the week. My ultimate goal is to have some cronjobs running which will update for things like injuries and price changes, then send a discord webhook if it's looking like they will impact the selected team.  (and eventually trigger the optimisation to run on AWS).
