### ISSUE TITLE
TypeError: case() got an unexpected keyword argument 'whens'

### ISSUE THREAD

**Issue by four-eyes-91** [alan-turing-institute/AIrsenal#623]
When I run any db updates, predicitions or the pipeline I get the error: 

TypeError: case() got an unexpected keyword argument 'whens'

---

Full error is: 

`airsenal_update_db
Traceback (most recent call last):
  File "/home/dnlocal/miniconda3/envs/airsenalenv/bin/airsenal_update_db", line 8, in <module> sys.exit(main())
  File "/home/dnlocal/miniconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/update_db.py", line 218, in main update_db(season, do_attributes, fpl_team_id, session)
  File "/home/dnlocal/miniconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/update_db.py", line 172, in update_db num_new_players = update_players(season, session)
  File "/home/dnlocal/miniconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/update_db.py", line 95, in update_players players_from_db = list_players(
  File "/home/dnlocal/miniconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/framework/utils.py", line 673, in list_players sort_order = case(value=PlayerAttributes.gameweek, whens=_whens)
TypeError: case() got an unexpected keyword argument 'whens'`

---

Please let me know if you need anymore info, thanks

**Comment by jack89roberts** [comment]
Hi @four-eyes-91 , this bug should now be fixed, try the following from the `AIrsenal` directory (where you cloned the repo):

```
conda activate airsenalenv
git pull
pip install --force-reinstall .
```

Then run AIrsenal as normal and it should work hopefully.
