### ISSUE TITLE
No commands available on built docker container

### ISSUE THREAD

**Issue by MrBennjjo** [alan-turing-institute/AIrsenal#629]
Have ran through and (seemingly) successfully built my docker container. When I come to try to actually run any commands within the container itself, absolutely nothing is recognised as a command. For example running `$ docker run -it --rm -v airsenal_data:/tmp/ -e "FPL_TEAM_ID=<your_id>" -e "AIRSENAL_HOME=/tmp" airsenal bash` results in the following error `docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "airsenal_run_pipeline": executable file not found in $PATH: unknown.`

**Comment by MrBennjjo** [comment]
hmm I might have been being an idiot, clearly I should have been running commands as `poetry run ...` from within the bash shell, that being said I am getting a new error now 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/airsenal/airsenal/scripts/fill_db_init.py", line 7, in <module>
    from airsenal.framework.schema import clean_database, database_is_empty, session_scope
  File "/airsenal/airsenal/framework/schema.py", line 444, in <module>
    session = get_session()
              ^^^^^^^^^^^^^
  File "/airsenal/airsenal/framework/schema.py", line 432, in get_session
    engine = create_engine(get_connection_string())
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/airsenal/airsenal/framework/schema.py", line 406, in get_connection_string
    if get_env("AIRSENAL_DB_FILE") and get_env("AIRSENAL_DB_URI"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/airsenal/airsenal/framework/env.py", line 36, in wrapper
    return func(key, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/airsenal/airsenal/framework/env.py", line 45, in get_env
    if os.path.exists(AIRSENAL_HOME / key):
                      ~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**Comment by nbarlowATI** [comment]
Hi @MrBennjjo ,  sorry to hear that this is causing trouble...
The problem here seems to be that AIRSENAL_HOME is a string rather than a path...   Looking at the code in `env.py` I guess that can happen if it is set from an environment variable.
I just pushed a quick fix to the `develop` branch - could you try that, and remake your docker image, and let us know if it fixes it?

**Comment by MrBennjjo** [comment]
Hi, will do - I actually fixed it locally by implementing a similar solution, apologies for not raising a PR with the fix in it!
