### ISSUE TITLE
`unsupported operand types` while running any AIrsenal commands in Docker

### ISSUE THREAD

**Issue by sam-cutter** [alan-turing-institute/AIrsenal#639]
I am running AIrsenal in Docker. I've build the image with the default Dockerfile, and ran the image with the provided `docker run` command, substituting my team ID and login. However, when I run any command, such as `poetry run airsenal_env get`, I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/airsenal/airsenal/scripts/set_env.py", line 11, in <module>
    from airsenal.framework.schema import session
  File "/airsenal/airsenal/framework/schema.py", line 444, in <module>
    session = get_session()
              ^^^^^^^^^^^^^
  File "/airsenal/airsenal/framework/schema.py", line 432, in get_session
    engine = create_engine(get_connection_string())
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/airsenal/airsenal/framework/schema.py", line 406, in get_connection_string
    if get_env("AIRSENAL_DB_FILE") and get_env("AIRSENAL_DB_URI"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/airsenal/airsenal/framework/env.py", line 36, in wrapper
    return func(key, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/airsenal/airsenal/framework/env.py", line 45, in get_env
    if os.path.exists(AIRSENAL_HOME / key):
                      ~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
This syntax of using the forward slash appears all throughout the code, in ways that I previously thought weren't possible with Python. Am I doing something wrong here?

**Comment by jack89roberts** [comment]
This is #629 , which we had a fix for but we hadn't merged to main yet. I've done that now so if you pull the latest version of the repo and rebuild the docker container it should work now (the `/` is something you can do with `pathlib.Path`, this was an edgecase where `AIRSENAL_HOME` was a `str` instead of a `Path` instance).
