### ISSUE TITLE
airsenal_run_prediction throwing errors after new install on a new WSL2/WIN 11 install

### ISSUE THREAD

**Issue by markajam** [alan-turing-institute/AIrsenal#657]
After an install on a new laptop I have had the following error dump when initiating  a 'run prediction'. 

DB updates and Db checks have all passed OK prior.

`(airsenalenv) mark@Mark-ZBook14uG6:~/AIrsenal$ airsenal_run_prediction --weeks_ahead 3
Traceback (most recent call last):
  File "/home/mark/miniconda3/envs/airsenalenv/bin/airsenal_run_prediction", line 5, in <module>
    from airsenal.scripts.fill_predictedscore_table import main
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 15, in <module>
    from bpl import ExtendedDixonColesMatchPredictor
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/bpl/__init__.py", line 4, in <module>
    from bpl.dixon_coles import DixonColesMatchPredictor
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/bpl/dixon_coles.py", line 9, in <module>
    import numpyro
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/__init__.py", line 6, in <module>
    from numpyro import compat, diagnostics, distributions, handlers, infer, ops, optim
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/infer/__init__.py", line 5, in <module>
    from numpyro.infer.elbo import (
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/infer/elbo.py", line 24, in <module>
    from numpyro.ops.provenance import eval_provenance
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/ops/provenance.py", line 10, in <module>
    import jax.linear_util as lu`

**Comment by markajam** [comment]
Hi @jack89roberts . oops. That was remiss of me to post incomplete info. Sorry.

`(airsenalenv) mark@Mark-ZBook14uG6:~$ airsenal_run_prediction --weeks_ahead 3
Traceback (most recent call last):
  File "/home/mark/miniconda3/envs/airsenalenv/bin/airsenal_run_prediction", line 5, in <module>
    from airsenal.scripts.fill_predictedscore_table import main
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 15, in <module>
    from bpl import ExtendedDixonColesMatchPredictor
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/bpl/__init__.py", line 4, in <module>
    from bpl.dixon_coles import DixonColesMatchPredictor
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/bpl/dixon_coles.py", line 9, in <module>
    import numpyro
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/__init__.py", line 6, in <module>
    from numpyro import compat, diagnostics, distributions, handlers, infer, ops, optim
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/infer/__init__.py", line 5, in <module>
    from numpyro.infer.elbo import (
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/infer/elbo.py", line 24, in <module>
    from numpyro.ops.provenance import eval_provenance
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/ops/provenance.py", line 10, in <module>
    import jax.linear_util as lu
ModuleNotFoundError: No module named 'jax.linear_util'
(airsenalenv) mark@Mark-ZBook14uG6:~$`

**Comment by markajam** [comment]
There is certainly no GPU on this HP elitebook laptop. :)  I did an export JAX_PLATFORM_NAME=cpu 

`(airsenalenv) mark@Mark-ZBook14uG6:~$ export JAX_PLATFORM_NAME=cpu
(airsenalenv) mark@Mark-ZBook14uG6:~$ airsenal_run_prediction --weeks_ahead 3
Traceback (most recent call last):
  File "/home/mark/miniconda3/envs/airsenalenv/bin/airsenal_run_prediction", line 5, in <module>
    from airsenal.scripts.fill_predictedscore_table import main
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 15, in <module>
    from bpl import ExtendedDixonColesMatchPredictor
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/bpl/__init__.py", line 4, in <module>
    from bpl.dixon_coles import DixonColesMatchPredictor
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/bpl/dixon_coles.py", line 9, in <module>
    import numpyro
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/__init__.py", line 6, in <module>
    from numpyro import compat, diagnostics, distributions, handlers, infer, ops, optim
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/infer/__init__.py", line 5, in <module>
    from numpyro.infer.elbo import (
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/infer/elbo.py", line 24, in <module>
    from numpyro.ops.provenance import eval_provenance
  File "/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/ops/provenance.py", line 10, in <module>
    import jax.linear_util as lu
ModuleNotFoundError: No module named 'jax.linear_util'
(airsenalenv) mark@Mark-ZBook14uG6:~$ printenv
SHELL=/bin/bash
WSL2_GUI_APPS_ENABLED=1
CONDA_EXE=/home/mark/miniconda3/bin/conda
_CE_M=
WSL_DISTRO_NAME=Ubuntu
XML_CATALOG_FILES=file:///home/mark/miniconda3/envs/airsenalenv/etc/xml/catalog file:///etc/xml/catalog
NAME=Mark-ZBook14uG6
PWD=/home/mark
LOGNAME=mark
CONDA_PREFIX=/home/mark/miniconda3/envs/airsenalenv
HOME=/home/mark
LANG=C.UTF-8
WSL_INTEROP=/run/WSL/354_interop
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
WAYLAND_DISPLAY=wayland-0
CONDA_PROMPT_MODIFIER=(airsenalenv)
JAX_PLATFORM_NAME=cpu
LESSCLOSE=/usr/bin/lesspipe %s %s
TERM=xterm-256color
_CE_CONDA=
LESSOPEN=| /usr/bin/lesspipe %s
USER=mark
CONDA_SHLVL=2
DISPLAY=:0
SHLVL=1
CONDA_PYTHON_EXE=/home/mark/miniconda3/bin/python
XDG_RUNTIME_DIR=/run/user/1000/
CONDA_DEFAULT_ENV=airsenalenv
WSLENV=
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/mark/miniconda3/envs/airsenalenv/bin:/home/mark/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Users/mark/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/mark/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
HOSTTYPE=x86_64
CONDA_PREFIX_1=/home/mark/miniconda3
PULSE_SERVER=unix:/mnt/wslg/PulseServer
OLDPWD=/home/mark/miniconda3/envs/airsenalenv/lib/python3.11/site-packages/numpyro/infer
_=/usr/bin/printenv
(airsenalenv) mark@Mark-ZBook14uG6:~$`

**Comment by jack89roberts** [comment]
It seems to be an incompatibility between `jax` and `numpyro` versions, if you try `pip install jax==0.4.23 jaxlib==0.4.23` it should work.

**Comment by markajam** [comment]
Indeed it does.
Many thanks for that.

Mark J
