### ISSUE TITLE
Get data for a new season

### ISSUE THREAD

**Issue by negmeme2001** [alan-turing-institute/AIrsenal#676]
While i'm trying to start work on new season 2425 so i want to know how do we add the required csv files for the model 
```bash
$ airsenal_setup_initial_db --clean
Cleaning database..
Filling Teams table from data in /media/mnegm/Negmos_Files/ProCrew/AIrsenal/airsenal/scripts/../data/teams_2425.csv
Traceback (most recent call last):
  File "/media/mnegm/Negmos_Files/anaconda3/ls/envs/airsenalenv/bin/airsenal_setup_initial_db", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/media/mnegm/Negmos_Files/ProCrew/AIrsenal/airsenal/scripts/fill_db_init.py", line 91, in main
    make_init_db(args.fpl_team_id, seasons, dbsession)
  File "/media/mnegm/Negmos_Files/ProCrew/AIrsenal/airsenal/scripts/fill_db_init.py", line 35, in make_init_db
    make_team_table(seasons=seasons, dbsession=dbsession)
  File "/media/mnegm/Negmos_Files/ProCrew/AIrsenal/airsenal/scripts/fill_team_table.py", line 49, in make_team_table
    fill_team_table_from_file(filename, dbsession=dbsession)
  File "/media/mnegm/Negmos_Files/ProCrew/AIrsenal/airsenal/scripts/fill_team_table.py", line 22, in fill_team_table_from_file
    infile = open(filename)
             ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/media/mnegm/Negmos_Files/ProCrew/AIrsenal/airsenal/scripts/../data/teams_2425.csv'
```

**Comment by nbarlowATI** [comment]
Hi @negmeme2001 , we haven't quite started preparing AIrsenal for the next season yet (there are also rule changes regarding the number of free transfers that can be banked, that we'll need to implement), but if you want to get a headstart and add this particular file, you can see the format from previous years e.g. `AIrsenal/airsenal/data/teams_2324.csv` - if you add a new file `teams_2425.csv` before doing `pip install .` it should be copied to the right place.
In terms of what to put in there, the teams are listed in alphabetical order according to the three-letter abreviations, so the new ones are "IPS"/"Ipswich", "LEI"/ "Leicester", and "SOU"/"Southampton".
Hope this helps!   We'll also post an update when AIrsenal is fully 24/25 ready...
