### ISSUE TITLE
RuntimeError: Squad is incomplete

### ISSUE THREAD

**Issue by RajeshTailor1** [alan-turing-institute/AIrsenal#683]
I have just set this up for the new season I have already setup a squad for my FPL team however I did setup my FPL Team ID in the env prior to running the make squad routine.

I think this error has come up a few times in the past but for some reason I can't remember how I resolved it the last time.

**Comment by jack89roberts** [comment]
A few comments/ideas:

- You can set your new team ID with `airsenal_env set -k FPL_TEAM_ID -v 123456` (and similarly for `FPL_PASSWORD` and `FPL_LOGIN` if those have changed). 
- If you've not already you'll need to pull the latest changes in the repo and then reinstall AIrsenal
- It's maybe worth running `airsenal_run_pipeline --clean`, which will delete and recreate the database for you.

If none of these fix it, what command are you running and could you post more of the error message you're getting?

**Comment by jack89roberts** [comment]
Also, if you're running individual commands separately, before the season starts only `airsenal_make_squad` will work, not `airsenal_run_optimization` (but `airsenal_run_pipeline` will do that automatically).

**Comment by AbdullaMashaly** [comment]
Traceback (most recent call last):
  File "/Users/abdullamashaly/anaconda3/envs/airsenalenv/bin/airsenal_make_squad", line 8, in <module>
    sys.exit(main())
  File "/Users/abdullamashaly/anaconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/squad_builder.py", line 208, in main
    fill_initial_squad(
  File "/Users/abdullamashaly/anaconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/scripts/squad_builder.py", line 73, in fill_initial_squad
    optimised_score = get_discounted_squad_score(
  File "/Users/abdullamashaly/anaconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/framework/optimization_utils.py", line 214, in get_discounted_squad_score
    total_points += squad.get_expected_points(gw, tag) * gw_weight
  File "/Users/abdullamashaly/anaconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/framework/squad.py", line 398, in get_expected_points
    self.optimize_lineup(gameweek, tag)
  File "/Users/abdullamashaly/anaconda3/envs/airsenalenv/lib/python3.9/site-packages/airsenal/framework/squad.py", line 385, in optimize_lineup
    raise RuntimeError("Squad is incomplete")
RuntimeError: Squad is incomplete

Same thing  Happens here !

**Comment by AbdullaMashaly** [comment]
This Happens When I try to run airsenal_make_squad --num_gameweeks 3

**Comment by AbdullaMashaly** [comment]
Yes I tried all the stuff from above but still have the same problem

**Comment by jack89roberts** [comment]
Hmm not sure what's going on then, could you check you get version `1.8.0` from `python -c "import airsenal; print(airsenal.__version__)"`? And are you able to test in a more recent version of Python in case that makes a difference (the conda environment in the readme currently sets up Python 3.12).

**Comment by AbdullaMashaly** [comment]
airsenal_make_squad --algorithm normal  worked but then ran into another problem when making transfers not sure what is wrong ... anyways thanks for your help

**Comment by jack89roberts** [comment]
If it was just `airsenal_make_transfers` that failed it might be something to do with setting your username/password/team ID, or occasionally we see captcha issues. Does `airsenal_run_pipeline` work for you now the season has started?

**Comment by RajeshTailor1** [comment]
Providing some additional context as I am still receiving the error.  However I haven't tried changing the algorithm yet. I updated the DB using the commands and I am running the individual commands not the pipeline. I have attached a screenshot of the error.
![Screenshot 2024-09-02 at 12 14 42](https://github.com/user-attachments/assets/ad330255-9a61-4846-be1c-90d472712231)

**Comment by nbarlowATI** [comment]
Hi @RajeshTailor1!   I don't think the choice of algorithm is relevant here - this is just for the initial squad selection via `airsenal_make_squad`, which would be used before Gameweek 1.    For the week-to-week `airsenal_run_optimization`, it just tries to find the best strategy over the next few gameweeks, where it can make 0, 1, or 2 transfers per week, and in each part of the determination (each node of the tree) it does an exhaustive search of e.g. what would be the best 2 transfers.

Another thing to check then would be that after doing `airsenal_setup_initial_db --clean` and `airsenal_update_db`, you have the correct squad - agreeing with what the FPL website thinks you have:
```
python
>>> from airsenal.framework.utils import NEXT_GAMEWEEK
>>> from airsenal.framework.optimization_utils import get_starting_squad
>>> print get_starting_squad(NEXT_GAMEWEEK)
```

If that looks ok, then, somewhere in the optimization itself it is failing to do the transfers its trying to do...   I think the only way to debug this would be to put some print statements into the `make_best_transfers` function in `airsenal/framework/optimization_transfers.py` - e.g. above line 395 you could do
`print(f"trying {num_transfers} transfers, squad is {new_squad}")` ?
