### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by radiaated** [alan-turing-institute/AIrsenal#684]
I tried to run command `airsenal_run_pipeline` using pip with Python3.9.

 I got the error as in the log:
`
Filling history dataframe for Nathan Wood-Gordon: 192/198 done
Filling history dataframe for Ashley Phillips: 193/198 done
Filling history dataframe for Aaron Cresswell: 194/198 done
Filling history dataframe for Ki-Jana Hoever: 195/198 done
Filling history dataframe for Yerson Mosquera: 196/198 done
Filling history dataframe for Pedro Cardoso de Lima: 197/198 done
Traceback (most recent call last):
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/bin/airsenal_run_pipeline", line 8, in <module>
    sys.exit(run_pipeline())
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/airsenal/scripts/airsenal_run_pipeline.py", line 200, in run_pipeline
    predict_ok = run_prediction(
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/airsenal/scripts/airsenal_run_pipeline.py", line 304, in run_prediction
    tag = make_predictedscore_table(
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 206, in make_predictedscore_table
    calc_all_predicted_points(
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/airsenal/scripts/fill_predictedscore_table.py", line 115, in calc_all_predicted_points
    df_player = get_all_fitted_player_data(
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/airsenal/framework/prediction_utils.py", line 631, in get_all_fitted_player_data
    df_positions[pos] = fit_player_data(pos, season, gameweek, model, dbsession)
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/airsenal/framework/prediction_utils.py", line 608, in fit_player_data
    data = process_player_data(position, season, gameweek, dbsession)
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/airsenal/framework/prediction_utils.py", line 569, in process_player_data
    alpha = get_empirical_bayes_estimates(df)
  File "/home/radiated/Documents/Project/AIrsenal-backend/penv/lib/python3.9/site-packages/airsenal/framework/player_model.py", line 39, in get_empirical_bayes_estimates
    a0 = n_matches * (player_goals / team_goals) * (total_minutes / player_minutes)
ZeroDivisionError: division by zero
`

**Comment by radiaated** [comment]
Yes, I'm running it Python3.9 

`airsenal_run_pipeline --clean` fixed the issue pretty much...

Thank you.

**Comment by radiaated** [comment]
Fixed with command: `airsenal_run_pipeline --clean`
